_reference_os: &reference_os
                 linux #sono stringhe equivalente a " " o ''
_reference_arch: &reference_arch
                 amd64 #nostra chiave
_reference_jdk: &reference_jdk #è una stringa
                  JDK="adopt@1.11"
_workspace_name: &workspace_name
                   compile_env

_import_workspace: &import_workspace
  workspaces:
    use: *workspace_name

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk

#limite: accodare elem in lista e concatenare stringhe
#si può fare merge di mappe

language: minimal #configuriamo noi

git:
  depth: false #
  autocrlf: input #

os:
  - *reference_os
  - osx
  - windows

dist: focal #ubuntu ultimo, ne ha di più, anche di Windows solo 10
#macOs osx_image: xcode9.4

arch:
  - *reference_arch
  - arm64

#mappa
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
    #- JDK="adopt-openj9@1.11" #deve funzionare con tutte le jdk
  matrix: #&pippo, per portarmi dietro la lista
    - *reference_jdk
    - JDK="adopt@1.14"
    - JDK="adopt@1.8"
    - JDK="adopt-openj9@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"

stages:
  - Compile
  - Kotlin Style Check
  - Complete check
  - test #default di travis

jobs:
  exclude:
    - arch: *reference_arch
      env: JDK="adopt-openj9@1.8"
    - arch: *reference_arch
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: Complete check
      script: travis_retry sh ./gradlew check
      *import_workspace
    - <<: *reference_machine
      stage: Compile
      script: sh ./gradlew compile
      workspaces:
        create: *workspace_name
        paths:
          - "$TRAVIS_BUILD_DIR"
          - "$HOME/.gradle" #non riscarichi il wrapper nè ricompilare buildgradlekts
    - <<: *reference_machine
      stage: Kotlin Style Check
      script: sh ./gradlew detekt ktlintCheck --parallel #non vale la pena risalvare ws, dipende da costo
      *import_workspace
      #workspaces:                                   #compilatore scala forse serve per evitare die seguire + volte
       # use: *workspace_name

before_install: #ambiente wind uso choco per installare java
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - true

script:
  - travis_retry sh ./gradlew test #sh per windows