language: minimal #configuriamo noi

git:
  depth: false #
  autocrlf: input #

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - JDK="adopt-openj9@1.11"

before_install: #ambiente wind uso choco per installare java
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - true

script:
  - travis_retry sh ./gradlew check #sh per windows